default: &default
  adapter: mysql2
  encoding: utf8
  local_infile: true
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  port: 3306

development:
  <<: *default
  database: teammaps_development

test:
  <<: *default
  database: teammaps_test

staging:
  <<: *default
  database: teammaps_stg
  username: <%= ENV['TEAMMAPS_DATABASE_USERNAME'] %>
  password: <%= ENV['TEAMMAPS_DATABASE_PASSWORD'] %>

production:
  <<: *default                                       
  database: teammaps_prd
  username: <%= ENV['TEAMMAPS_DATABASE_USERNAME'] %>
  password: <%= ENV['TEAMMAPS_DATABASE_PASSWORD'] %>
  host: <%= ENV['TEAMMAPS_DATABASE_HOST'] %>
